workflow(15-matrices) - understanding the include option further

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -3,40 +3,40 @@ on:
   workflow_dispatch:
 
 jobs:
-  backwards-compatibility:
-    name: "${{ matrix.os }}-${{ matrix.node-version }}"
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        node-version: ['18.x', '19.x', '20.x']
-        os: [ubuntu-latest, windows-latest]
-        include:
-          - os: ubuntu-latest
-            node-version: 16.x
-          - os: ubuntu-latest
-            node-version: 21.x
-            tag: experimental
-      fail-fast: false
+  # backwards-compatibility:
+  #   name: "${{ matrix.os }}-${{ matrix.node-version }}"
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       node-version: ['18.x', '19.x', '20.x']
+  #       os: [ubuntu-latest, windows-latest]
+  #       include:
+  #         - os: ubuntu-latest
+  #           node-version: 16.x
+  #         - os: ubuntu-latest
+  #           node-version: 21.x
+  #           tag: experimental
+  #     fail-fast: false
 
-    steps:
-      - name: "setup-node"
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
+  #   steps:
+  #     - name: "setup-node"
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
 
-      - name: "Fail if exprimental"
-        if: matrix.tag == 'experimental'
-        run: |
-          exit 1
+  #     - name: "Fail if exprimental"
+  #       if: matrix.tag == 'experimental'
+  #       run: |
+  #         exit 1
           
-      - name: "Perform some tests"
-        run: |
-          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
-          sleep 10
+  #     - name: "Perform some tests"
+  #       run: |
+  #         echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
+  #         sleep 10
 
-      - name: "Upoading test results"
-        run: |
-          echo "Uploading test results"
+  #     - name: "Upoading test results"
+  #       run: |
+  #         echo "Uploading test results"
 
   include-example:
     name: "${{ matrix.color }}-${{matrix.shape}}-${{matrix.size}}-${{ matrix.opacity}}"
@@ -47,13 +47,13 @@ jobs:
         shape: ["circle", "square"]
         size: ["small", "large"]
         include:
-          - opacity: 50
           - color: red
             opacity: 75
           - shape: circle
             opacity: 100
           - color: red
             shape: triangle
+          - opacity: 50
     steps:
       - name: "Dummyy Step"
         run: |
